#!/bin/bash
PWD=$(pwd)
CHECK=0
TIMER=0
PRINT=0
CONFIG=""

while getopts ":tcpa:" opt; do
        case $opt in
                t)
                        echo "Setting timer"
                        TIMER=1
                        ;;
                p)
                        echo "Printing commands before running..."
                        PRINT=1
                        ;;
                c)
                        echo "Running checks..."
                        CHECK=1
                        ;;
                a)
                        echo "Appending configure file with: $OPTARG" >&2
                        CONFIG=$OPTARG
                        ;;
                \?)
                        echo "Invalid option: -$OPTARG" >&2
                        ;;
                :)
                        echo "Option -$OPTARG requires an argument." >&2
                        exit 1
                        ;;
        esac
done

shift $((OPTIND-1))

while [ $# -ne 0 ]; do
        FILE=$1

        if [ $PRINT = 1 ]; then
                echo "Installing package: $1"
                echo "Examine the commands before continuing:"
                echo "tar xvf $FILE"
                echo "cd ${FILE%%.tar*}"
                echo "./configure --prefix=/usr $CONFIG"
                echo "make"
                if [ $CHECK = 1 ]; then
                        echo "make check"
                fi
                echo "make install"
                echo "cd $PWD"
                echo "rm -rvf $PWD/${FILE%%.tar*}"

                while true; do
                        read -p "Are you sure you want to install $1? " yn
                        case $yn in 
                                [Yy]* ) break;;
                                * ) exit;; 
                        esac
                done
        fi

        time {

        tar xvf $FILE
        cd ${FILE%%.tar*}

        ./configure --prefix=/usr $CONFIG
        make

        if [ $CHECK = 1 ]; then
                make check 
        fi

        make install

        cd ..
        rm -rvf "$PWD"/"${FILE%%.tar*}"
        }
        echo "Package $1 installed succesfully!"
        break
done
