#!/bin/bash

# Set variables
NW_LOG_FILE=/var/log/networkscriptlog/$(date +%s)-network-debug.log
WPA_CONF_FILE=/etc/wpa_supplicant/sky.conf

echo "Starting network" $WPA_CONF_FILE
wpa_supplicant -t -dd -f $NW_LOG_FILE -B -i wlp10s0 -c $WPA_CONF_FILE
echo "Starting dhcpcd"
dhcpcd -4 wlp10s0 &> $NW_LOG_FILE
if [ $(curl --silent -o /dev/null google.com | echo ${PIPESTATUS}) = 0 ]; then
	echo "Connected to google.com"
else
	echo "Error with connection - look at" $NW_LOG_FILE
fi
echo "Script finished"
